### ISSUE TITLE
`require': cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by Amakata** [Amakata/cfndk#13]
```
[root@localhost ~]# cfndk -v
/opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/cfndk-0.1.1.1/lib/cfndk.rb:1:in `<top (required)>'
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/cfndk-0.1.1.1/bin/cfndk:5:in `<top (required)>'
	from /opt/rh/rh-ruby24/root/usr/local/bin/cfndk:23:in `load'
	from /opt/rh/rh-ruby24/root/usr/local/bin/cfndk:23:in `<main>'
[root@localhost ~]# gem install bundle
Fetching: bundler-2.0.2.gem (100%)
Successfully installed bundler-2.0.2
Fetching: bundle-0.0.1.gem (100%)
Successfully installed bundle-0.0.1
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundler, bundle after 7 seconds
2 gems installed
[root@localhost ~]# cfndk -v
Commands:
  cfndk changeset SUBCOMMAND ...ARGS  # Manage change set
  cfndk create                        # Create keypair & stack
  cfndk destroy                       # Destroy keypair & stack
  cfndk generate-uuid                 # Print UUID
  cfndk help [COMMAND]                # Describe available commands or one specific command
  cfndk init                          # Craete sample cfndk.yml & CloudFormation yaml & json files.
  cfndk keypair SUBCOMMAND ...ARGS    # Manage keypair
  cfndk report                        # Report stack
  cfndk stack SUBCOMMAND ...ARGS      # Manage stack
  cfndk version                       # Print version

Options:
  v, [--verbose], [--no-verbose]  # More verbose output.
      [--color], [--no-color]     # Use colored output
                                  # Default: true

**Comment by Amakata** [comment]
https://github.com/Amakata/cfndk/pull/14
